services:
  postgres_core:
    image: postgres:latest
    container_name: core_postgres_db
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_user
    ports:
      - "5432:5432"  # Maps port 5432 on your machine to port 5432 in the container, diff containers can run on same port since they run on diff network instances
    volumes:
      - ./backend/core-service/core-postgres-data:/var/lib/postgresql/data  # Persists data on local filesystem

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migration
    depends_on:
      - postgres_core
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres_core:5432/e-commerce  # Point to the postgres service
      FLYWAY_USER: ecommerce_user
      FLYWAY_PASSWORD: ecommerce_user
    command: -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./backend/core-service/src/main/resources/sql/migration:/flyway/sql  #Adjust to relative path of SQL files

  # Payment service PostgreSQL container
  postgres_payment:
    image: postgres:latest
    container_name: payment_postgres_db
    environment:
      POSTGRES_DB: payment_db  # Payment database name
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_user
    ports:
      - "5433:5432"  # Maps localhost:5433 to container's port 5432
    volumes:
      - ./backend/payment/payment-postgres-data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak-e_commerce
    image: quay.io/keycloak/keycloak:25.0.5
    ports:
      - "9090:8443" #Map Docker's internal HTTPS port 8443 to localhost 9090
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/keycloak-keystore.p12 #specifies the path to the keystore inside the container
      KC_HTTPS_KEY_STORE_PASSWORD: secret
      KC_HOSTNAME: localhost
    volumes:
      - ./keycloak-keystore.p12:/opt/keycloak/conf/keycloak-keystore.p12 #mount keycloak-keystore.p12 inside container
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json # Mount realm-export.json inside container
    command:
      - "start-dev"


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 2097152
    ports:
      - "9092:9092"
