version: '3.8'

services:
  postgres:
    image: postgres:latest  # Use the latest version of the official PostgreSQL image
    container_name: postgres_db  # Optional: you can name your container
    environment:
      POSTGRES_DB: e-commerce  # This is your database name
      POSTGRES_USER: ecommerce_user  # This is your username
      POSTGRES_PASSWORD: ecommerce_user  # Replace with a strong password
    ports:
      - "5432:5432"  # Maps port 5432 on your machine to port 5432 in the container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Persist data on your local filesystem
#      - ./db_setup.sql:/docker-entrypoint-initdb.d/e-commerce-db.sql  # Run your SQL script during container startup

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migration
    depends_on:
      - postgres
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/e-commerce  # Point to the postgres service
      FLYWAY_USER: ecommerce_user
      FLYWAY_PASSWORD: ecommerce_user
    command: -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./backend/core-service/src/main/resources/sql/migration:/flyway/sql  #Adjust to relative path of SQL files

  keycloak:
    container_name: keycloak-e_commerce
    image: quay.io/keycloak/keycloak:25.0.5
    ports:
      - "9090:8443" #Map Docker's internal HTTPS port 8443 to localhost 9090
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/keycloak-keystore.p12 #specifies the path to the keystore inside the container
      KC_HTTPS_KEY_STORE_PASSWORD: secret
      KC_HOSTNAME: localhost
    volumes:
      - ./keycloak-keystore.p12:/opt/keycloak/conf/keycloak-keystore.p12 #mount keycloak-keystore.p12 inside container
    command:
      - "start-dev"
